FROM jupyter/base-notebook:python-3.9.13

USER root

# Install OS dependencies
RUN apt-get update
RUN apt-get install -y git-core ffmpeg espeak-ng wget gnupg
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

# Install CUDA
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
RUN dpkg -i cuda-keyring_1.1-1_all.deb
RUN apt-get update
RUN apt-get -y install cuda-toolkit-12-5

# Update Conda, create the voicecraft environment, and install dependencies
RUN conda update -y -n base -c conda-forge conda
RUN conda create -y -n voicecraft python=3.9.16
RUN conda run -n voicecraft conda install -y -c conda-forge montreal-forced-aligner=2.2.17 openfst=1.8.2 kaldi=5.5.1068
RUN conda run -n voicecraft mfa model download dictionary english_us_arpa
RUN conda run -n voicecraft mfa model download acoustic english_us_arpa
RUN conda run -n voicecraft pip install -U audiocraft
RUN conda run -n voicecraft pip install -U git+https://git@github.com/facebookresearch/audiocraft#egg=audiocraft
RUN conda run -n voicecraft pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
RUN conda run -n voicecraft pip install tensorboard==2.16.2
RUN conda run -n voicecraft pip install phonemizer==3.2.1
RUN conda run -n voicecraft pip install datasets==2.16.0
RUN conda run -n voicecraft pip install torchmetrics==0.11.1
RUN conda run -n voicecraft pip install huggingface_hub==0.22.2
RUN conda run -n voicecraft pip install xformers

# Install the Jupyter kernel
RUN conda install -n voicecraft ipykernel --update-deps --force-reinstall -y && \
    conda run -n voicecraft python -m ipykernel install --name=voicecraft

# Set NVIDIA environment variables
ENV PATH /usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:${LD_LIBRARY_PATH}

# Enable NVIDIA runtime
LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

# docker build -f DockerFile-3 -t voicecraft-3 .
# docker run --rm -it -p 8888:8888 --gpus all voicecraft-3
